### ISSUE TITLE
Can't find element 

### ISSUE THREAD

**Issue by MeteorSwarm** [wuuconix/DifferentDimensionMeAPI#1]
{"error":"Error: No element found for selector: img[src='https://shadow-h5-prd-1251316161.file.myqcloud.com/oss/1/choose_2.png']"}

34 line, index.mjs

**Comment by wuuconix** [comment]
> 

**Yes**, some error is there! Tencent has made this page https://h5.tu.qq.com/web/ai-2d/cartoon/index can only open from mobile qq, so code is temporarily broken, i will fix it as fast as i can.
