### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nevze** [wuuconix/DifferentDimensionMeAPI#3]
{"error":"ReferenceError: fetchOptions is not defined"}

**Comment by wuuconix** [comment]
This is a weird error. I tried in multiple machines but cannot reproduce this bug.

`fetchOptions` is explicitly declared here which aims to support http proxy.
https://github.com/wuuconix/DifferentDimensionMeAPI/blob/22dbc5b833f932c02b6a5ff95e8d719a363f2e08/index.mjs#L8

If you still occur this error. Just delete the `fetchOptions` in https://github.com/wuuconix/DifferentDimensionMeAPI/blob/22dbc5b833f932c02b6a5ff95e8d719a363f2e08/index.mjs#L17

which may look this.
```js
let res = await fetch(url)
```

However, after you change, the program will lose the ability of proxy which is important in China.

If you don't live in China, feel free to remove `fetchOptions` in program.

**Comment by nevze** [comment]
fixed, thankyou
