### ISSUE TITLE
Add China Proxy

### ISSUE THREAD

**Issue by nevze** [wuuconix/DifferentDimensionMeAPI#4]
how to add china proxy?

**Comment by wuuconix** [comment]
https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999 supports China proxy now.

just input the China Proxy here.
https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
For example:
```js
const chinaProxy = "http://114.114.114.114:7890" 
```

**Comment by nevze** [comment]
> [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) supports China proxy now.
> 
> just input the China Proxy here.
> 
> https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> 
> 
> For example:
> ```js
> const chinaProxy = "http://114.114.114.114:7890" 
> ```

thankyou

**Comment by ibengarin** [comment]
{"error":"FetchError: request to https://ai.tu.qq.com/trpc.shadow_cv.ai_processor_cgi.AIProcessorCgi/Process failed, reason: connect ETIMEDOUT 0.0.36.227:80"}

**Comment by wuuconix** [comment]
> {"error":"FetchError: request to https://ai.tu.qq.com/trpc.shadow_cv.ai_processor_cgi.AIProcessorCgi/Process failed, reason: connect ETIMEDOUT 0.0.36.227:80"}

I think the problem comes from the `chinaProxy` you input.
make sure your chinaProxy is valid.

**Comment by ibengarin** [comment]
> > {"error":"FetchError: request to https://ai.tu.qq.com/trpc.shadow_cv.ai_processor_cgi.AIProcessorCgi/Process failed, reason: connect ETIMEDOUT 0.0.36.227:80"}
> 
> I think the problem comes from the `chinaProxy` you input. make sure your chinaProxy is valid.



address | Port | Country, City | Speed | Type | Anonymity
-- | -- | -- | -- | -- | --
111.40.124.221 | 9091 | China  Harbin | 1322 мс | HTTP | High

**Comment by wuuconix** [comment]
> > > {"error":"FetchError: request to https://ai.tu.qq.com/trpc.shadow_cv.ai_processor_cgi.AIProcessorCgi/Process failed, reason: connect ETIMEDOUT 0.0.36.227:80"}
> > 
> > 
> > I think the problem comes from the `chinaProxy` you input. make sure your chinaProxy is valid.
> 
> address	Port	Country, City	Speed	Type	Anonymity
> 111.40.124.221	9091	China  Harbin	1322 мс	HTTP	High

I tried your proxy in browser using [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega).
But cannot get the correct response of Tencent API.
So I still think that your proxy has some problem.
![image](https://user-images.githubusercontent.com/80732538/213095439-ead90a43-cfc1-4044-9f08-47a62792ec32.png)
![image](https://user-images.githubusercontent.com/80732538/213095972-e78496b5-7ed6-43db-a17d-8e41547c14a4.png)

**Comment by ibengarin** [comment]
> [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) supports China proxy now.
> 
> just input the China Proxy here.
> 
> https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> 
> 
> For example:
> ```js
> const chinaProxy = "http://114.114.114.114:7890" 
> ```



> > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) supports China proxy now.
> > just input the China Proxy here.
> > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > 
> > For example:
> > ```js
> > const chinaProxy = "http://114.114.114.114:7890" 
> > ```
> 
> thankyou

Use http ?

**Comment by ibengarin** [comment]
> > > > {"error":"FetchError: request to https://ai.tu.qq.com/trpc.shadow_cv.ai_processor_cgi.AIProcessorCgi/Process failed, reason: connect ETIMEDOUT 0.0.36.227:80"}
> > > 
> > > 
> > > I think the problem comes from the `chinaProxy` you input. make sure your chinaProxy is valid.
> > 
> > 
> > address	Port	Country, City	Speed	Type	Anonymity
> > 111.40.124.221	9091	China  Harbin	1322 мс	HTTP	High
> 
> I tried your proxy in browser using [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega). But cannot get the correct response of Tencent API. So I still think that your proxy has some problem. ![image](https://user-images.githubusercontent.com/80732538/213095439-ead90a43-cfc1-4044-9f08-47a62792ec32.png) ![image](https://user-images.githubusercontent.com/80732538/213095972-e78496b5-7ed6-43db-a17d-8e41547c14a4.png)

![Uploading Screenshot_20230119-122825.jpg…]()

**Comment by wuuconix** [comment]
> > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) supports China proxy now.
> > just input the China Proxy here.
> > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > 
> > For example:
> > ```js
> > const chinaProxy = "http://114.114.114.114:7890" 
> > ```
> 
> > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) supports China proxy now.
> > > just input the China Proxy here.
> > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > 
> > > For example:
> > > ```js
> > > const chinaProxy = "http://114.114.114.114:7890" 
> > > ```
> > 
> > 
> > thankyou
> 
> Use http ?

Yes, the proxy protocol should be http. Because I used https://www.npmjs.com/package/https-proxy-agent which only support http and https.

**Comment by ibengarin** [comment]
> > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang. 
> > > cukup masukkan Proxy China di sini.
> > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > 
> > > Sebagai contoh:
> > > ```js
> > > const chinaProxy = "http://114.114.114.114:7890" 
> > > ```
> > 
> > 
> > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang. 
> > > > cukup masukkan Proxy China di sini.
> > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > 
> > > > Sebagai contoh:
> > > > ```js
> > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > ```
> > > 
> > > 
> > > terima kasih
> > 
> > 
> > Gunakan http?
> 
> Ya, protokol proxy harus http. Karena saya menggunakan https://www.npmjs.com/package/https-proxy-agent yang hanya mendukung http dan https.

![Screenshot_20230120-174618](https://user-images.githubusercontent.com/56824876/213677281-e08ff0f5-2a11-4ff8-9438-d7f0b732ed9e.jpg)
Is it like this

**Comment by wuuconix** [comment]
> > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > cukup masukkan Proxy China di sini.
> > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > 
> > > > Sebagai contoh:
> > > > ```js
> > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > ```
> > > 
> > > 
> > > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > > cukup masukkan Proxy China di sini.
> > > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > > 
> > > > > Sebagai contoh:
> > > > > ```js
> > > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > > ```
> > > > 
> > > > 
> > > > terima kasih
> > > 
> > > 
> > > Gunakan http?
> > 
> > 
> > Ya, protokol proxy harus http. Karena saya menggunakan https://www.npmjs.com/package/https-proxy-agent yang hanya mendukung http dan https.
> 
> ![Screenshot_20230120-174618](https://user-images.githubusercontent.com/56824876/213677281-e08ff0f5-2a11-4ff8-9438-d7f0b732ed9e.jpg) Is it like this

Yes, It's looking good.

**Comment by ibengarin** [comment]
> > > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > > cukup masukkan Proxy China di sini.
> > > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > > 
> > > > > Sebagai contoh:
> > > > > ```js
> > > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > > ```
> > > > 
> > > > 
> > > > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > > > cukup masukkan Proxy China di sini.
> > > > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > > > 
> > > > > > Sebagai contoh:
> > > > > > ```js
> > > > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > > > ```
> > > > > 
> > > > > 
> > > > > terima kasih
> > > > 
> > > > 
> > > > Gunakan http?
> > > 
> > > 
> > > Ya, protokol proxy harus http. Karena saya menggunakan https://www.npmjs.com/package/https-proxy-agent yang hanya mendukung http dan https.
> > 
> > 
> > ![Screenshot_20230120-174618](https://user-images.githubusercontent.com/56824876/213677281-e08ff0f5-2a11-4ff8-9438-d7f0b732ed9e.jpg) Is it like this
> 
> Yes, It's looking good.

![Screenshot_20230120-180240](https://user-images.githubusercontent.com/56824876/213680437-9e0effb4-37a6-4062-890a-3c5c3e1410dd.jpg)

does it not support using vps?

**Comment by wuuconix** [comment]
> > > > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > > > cukup masukkan Proxy China di sini.
> > > > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > > > 
> > > > > > Sebagai contoh:
> > > > > > ```js
> > > > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > > > ```
> > > > > 
> > > > > 
> > > > > > > [27c0fd4](https://github.com/wuuconix/DifferentDimensionMeAPI/commit/27c0fd438041d2e8d269c54d587eb12033f17999) mendukung proxy China sekarang.
> > > > > > > cukup masukkan Proxy China di sini.
> > > > > > > https://github.com/wuuconix/DifferentDimensionMeAPI/blob/27c0fd438041d2e8d269c54d587eb12033f17999/index.mjs#L17
> > > > > > > 
> > > > > > > Sebagai contoh:
> > > > > > > ```js
> > > > > > > const chinaProxy = "http://114.114.114.114:7890" 
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > terima kasih
> > > > > 
> > > > > 
> > > > > Gunakan http?
> > > > 
> > > > 
> > > > Ya, protokol proxy harus http. Karena saya menggunakan https://www.npmjs.com/package/https-proxy-agent yang hanya mendukung http dan https.
> > > 
> > > 
> > > ![Screenshot_20230120-174618](https://user-images.githubusercontent.com/56824876/213677281-e08ff0f5-2a11-4ff8-9438-d7f0b732ed9e.jpg) Is it like this
> > 
> > 
> > Yes, It's looking good.
> 
> ![Screenshot_20230120-180240](https://user-images.githubusercontent.com/56824876/213680437-9e0effb4-37a6-4062-890a-3c5c3e1410dd.jpg)
> 
> does it not support using vps?

This error should not happen.
Can you type `node -v` to see your node version?
I think it is caused by too low level of node version.

**Comment by ibengarin** [comment]
![Screenshot_20230120-191051](https://user-images.githubusercontent.com/56824876/213692305-62eb6b0d-8381-490e-8e9d-06fa0f16047b.jpg)

root@Ubuntu-Ribeng:~# cd DifferentDimensionMeAPI
root@Ubuntu-Ribeng:~/DifferentDimensionMeAPI# npm i
npm WARN DifferentDimensionMeAPI No repository field.
npm WARN DifferentDimensionMeAPI No license field.

audited 74 packages in 5.227s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@Ubuntu-Ribeng:~/DifferentDimensionMeAPI# node index.mjs
/root/DifferentDimensionMeAPI/index.mjs:1
import { v4 as uuidv4 } from 'uuid'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
root@Ubuntu-Ribeng:~/DifferentDimensionMeAPI# node -v
v10.19.0

**Comment by wuuconix** [comment]
> root@Ubuntu-Ribeng:~/DifferentDimensionMeAPI# node -v v10.19.0

version 10.19.0 is too low.
You should upgrade it to the Latest LTS version which should be 18.13.0.
Learn More: https://nodejs.org/en/
https://github.com/nvm-sh/nvm

**Comment by ibengarin** [comment]
> > root@Ubuntu-Ribeng:~/DifferentDimensionMeAPI# node -v v10.19.0
> 
> version 10.19.0 is too low. You should upgrade it to the Latest LTS version which should be 18.13.0. Learn More: https://nodejs.org/en/ https://github.com/nvm-sh/nvm

thank you.. now i want to find a proxy 😁 can you give me a proxy

**Comment by wuuconix** [comment]
> thank you.. now i want to find a proxy 😁 can you give me a proxy

It's impossible to find a free alive proxy. Don't waste your time searching and just buy it somewhere.
See more: https://github.com/lmcsu/qq-neural-anime-tg#mode-and-proxies

**Comment by ibengarin** [comment]
> > thank you.. now i want to find a proxy 😁 can you give me a proxy
> 
> It's impossible to find a free alive proxy. Don't waste your time searching and just buy it somewhere. See more: https://github.com/lmcsu/qq-neural-anime-tg#mode-and-proxies

![Screenshot_20230120-195956](https://user-images.githubusercontent.com/56824876/213700827-37285452-a830-4bb8-8727-fb99bc3523e4.jpg)

Why?

**Comment by wuuconix** [comment]
> Why?

That's the best.

**Comment by ibengarin** [comment]
> > ![Tangkapan layar_20230120-195956](https://user-images.githubusercontent.com/56824876/213700827-37285452-a830-4bb8-8727-fb99bc3523e4.jpg)
> > Mengapa?
> 
> Itu yang terbaik.

![Screenshot_20230119-122825](https://user-images.githubusercontent.com/56824876/213701600-53a61781-4e09-4904-ac99-fd6eaface8ad.jpg)
thank you, I can use the get proxy tool and connect to the ai

**Comment by ibengarin** [comment]
> > Why?
> 
> That's the best.

![Screenshot_20230122-145037](https://user-images.githubusercontent.com/56824876/213905929-e126aefa-3594-4e7f-ba30-7ed634bee0f9.jpg)
![Screenshot_20230122-144909](https://user-images.githubusercontent.com/56824876/213905934-7f3d323c-0dd0-4707-8bd6-23c9e17bac1d.jpg)

Why are my results different? and there is no video version either

**Comment by wuuconix** [comment]
> Why are my results different? and there is no video version either

Please open a new issue. This question is out of topic in this issue.

**Comment by wuuconix** [comment]
For everyone who has not a alive chinese proxy.
Please see this issue.
https://github.com/wuuconix/DifferentDimensionMeAPI/issues/7#issuecomment-1399428992
use the `aiplay_ai_painting_anime_entry` as `busiId` may not need a proxy. Because it is open to the world.
