### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by nevze** [wuuconix/DifferentDimensionMeAPI#5]
Hi, can u add feature for cropped image?

**Comment by nevze** [comment]
like this 
https://github.com/luiscruzga/selfieToAnime/blob/main/src/index.js

**Comment by wuuconix** [comment]
I'm sorry that I think this repository should keep slim and simple.
It's work only concentrates on fetching an image from Internet and then request the image to the Tencent API.
Maybe you can fork this repository and add your demands to it.

**Comment by nevze** [comment]
ah okay thankyou
